# Generated by Django 4.1.1 on 2022-10-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="phone",
            field=models.CharField(default="", max_length=10),
        ),
    ]
